spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver 
    type: com.alibaba.druid.pool.DruidDataSource
    
  redis:
    port: 6379
    
  thymeleaf:
    prefix: classpath:/static/temp/
    content-type: text/html
    encoding: UTF-8
    suffix: .html
    cache: false      
    
  profiles:
    active: master
    

logging:
  config: classpath:logback/logback-boot.xml 
    
#    minIdle: 1
#    maxActive: 2
#    initialSize: 1
#    timeBetweenEvictionRunsMillis: 3000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT 'ZTM' FROM DUAL
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false

mybatis:
  mapper-locations: classpath:com/pj/*/mapper/*.xml 
  type-aliases-package: com.pj.*.pojo





server:
  port: 8082
 
oa : 
  adminId: 8732
  url: http://10.0.0.18:8083
  ssoUrl: http://10.0.0.18:8085
    
---
spring:
  profiles: dev
  datasource:
    username: root
    password: root
    url: jdbc:mysql://10.0.0.18:3306/prm
  
  redis:
    host: 10.0.0.18
    password: redis

---
spring:
  profiles: master
  datasource:
    username: eams
    password: pjdb@EAMS
    url: jdbc:mysql://139.129.236.180:3306/eams
  
  redis:
    host: 139.129.236.180
    password: pj@redis_oa

oa:
  url: http://139.129.236.180:8080
  ssoUrl: http://139.129.236.180:8081
    
 
  